Add -Wno-uninitialized -Wno-unused-variable to avoid configure error
Here is content of objs/autoconf.err without these options.

checking for SA_RESTART
objs/autotest.c: In function 'main':
objs/autotest.c:8:32: error: 'act.sa_flags' is used uninitialized in this function [-Werror=uninitialized]
                   act.sa_flags |= SA_RESTART;;
                                ^
cc1: all warnings being treated as errors
----------
int main(void) {
    struct sigaction act;
                  act.sa_flags |= SA_RESTART;;
    return 0;
}
----------
cc -I/usr/include/luajit-2.1 -I/usr/include/luajit-2.1 -I/usr/include/luajit-2.1 -pipe -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -DTCP_FASTOPEN=23 -DNDK_SET_VAR -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -o objs/autotest objs/autotest.c
----------
----------------------------------------
checking for require defined symbols (--require-defined)
----------------------------------------
checking for MaxmindDB library
objs/autotest.c: In function 'main':
objs/autotest.c:7:12: error: unused variable 'mmdb' [-Werror=unused-variable]
     MMDB_s mmdb;
            ^
cc1: all warnings being treated as errors
----------
int main(void) {
    MMDB_s mmdb;
    return 0;
}
----------
cc -I/usr/include/luajit-2.1 -I/usr/include/luajit-2.1 -I/usr/include/luajit-2.1 -pipe -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -DTCP_FASTOPEN=23 -DNDK_SET_VAR -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -o objs/autotest objs/autotest.c -lmaxminddb
----------